[build]
  publish = "."
  command = ""

[context.production]
  command = ""

[[redirects]]
  from = "https://oncle-g.netlify.app/sitemap.xml"
  to = "/sitemap-netlify.xml"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  NODE_VERSION = "18"

[functions]
  directory = "functions"
  external_node_modules = ["sharp"]

[dev]
  command = ""
  port = 8888
  publish = "."
  autoLaunch = false